### ISSUE TITLE
Feature Request -- Print entityID / grid name with in-game messages

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#4]
Is it possible to add as a feature that when one runs a gridbackup command - like a manual "!gridbackup save" or "!gridbackup restore"; that it prints the EntityID of the grid being saved/restored/acted upon when it prints out the in-game chat message? Right now it just says something along the lines of "Grid Saved"; and for restores it does at least give the filename of the sbc backup.

Even if it's only added to saves as a way to *know* which grid entityID was just saved would be awesome

**Comment by LordTylus** [comment]
Hmm I can see what you mean.

yeah for restores I didnt see it necessary as you probably selected the grid to restore based on whatever you saw on grid slist.

also for restores you would have a bit of a conflict. would you want to see the ID the grid has after restoring or id the file has. Because after restore the grid gets a new ID. Restores however do log the full file path to the console and logfiles. 

For saves I think I can add something like that. Will put it on my pule of things to do

**Comment by kontu** [comment]
Restores are fine to stay the way they are to me. The biggest one would be for saves -- we have blocklimits we have to manually enforce currently, and when we find offending grids we force a gridbackup save of the grid and then remove it from the world -- it'd be nice if we could quickly document with a screenshot or logs or something showing the entity ID for when time to restore it again comes

**Comment by LordTylus** [comment]
Added in v1.0.3.3
