### ISSUE TITLE
Use Steam ID

### ISSUE THREAD

**Issue by bodyboarder2528** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#6]
any chance to be able to use steam ID as i am admin on the server and just havent been on for 3 days and then came back to find my player Id was removed and i have another one now and the gridbackup now doesnt like to my new player ID.

**Comment by LordTylus** [comment]
I can make it a setting to use Steam ID instead of Identitiy ID. Identity ID however will still be the default.

**Comment by bodyboarder2528** [comment]
sweet thanks no way for it to read both?

**Comment by LordTylus** [comment]
Nope as I just look up the folder name
and when the Identity is deleted I will never get the ID again as its physically not there anymore

so I have to replace that ID with steam ID. and easiest way to do it is to either spave by steam ID or save by identity ID

**Comment by bodyboarder2528** [comment]
ok thanks steam ID would be easier aswell as players can get there steam id easier plus SEDB now shows steam ID on connection and disconnection
![image](https://user-images.githubusercontent.com/49468427/88453153-f4320300-cea7-11ea-81ec-a7f60006c023.png)

**Comment by LordTylus** [comment]
Well Ill see what I can do about it.

**Comment by LordTylus** [comment]
@bodyboarder2528 I remember why I did not use steamID in the first place.

The thing is the game only works with identity ids. I of course can save them for a steam ID, however if for whatever reason the identity ID is deleted or now belongs to someone else because the world was wiped the imported grid may belong to an entirely different person.

So it would require you to fix owner and authorship manually after restoring something from the backup.

Which is why this feature would be experimental at best and definitely never be the default behavior as long as stuff like !sandbox clean is still a thing. 

I have not added that yet, but thought I let you know

**Comment by bodyboarder2528** [comment]
Ok cheers for the heads up

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LordTylus** [comment]
Added in v1.0.3.9
